# Install R version 3.5
FROM rocker/shiny:latest

# Install Ubuntu packages
RUN apt-get update && apt-get --no-install-recommends install -y \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    xtail \
    libjq-dev \
    libgeos-dev \
    libgdal-dev


RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean

RUN useradd --no-log-init -r -m -g staff ruser

# Copy configuration files into the Docker image
COPY ./renv.lock ./renv.lock

USER ruser

# install renv & restore packages
RUN Rscript -e 'install.packages("renv")'
RUN Rscript -e 'renv::restore()'

CMD tail -f /dev/null
