# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and push Docker image to Google Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
    docker:
        permissions:
          contents: 'read'
          id-token: 'write'
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - id: auth
            name: Authenticate with Google Cloud
            uses: google-github-actions/auth@v0
            with:
              token_format: 'access_token'
              credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          - name: setup gcloud tools
            uses: 'google-github-actions/setup-gcloud@v1'
            with:
              version: '>= 416.0.0'

          - name: copy files from bucket
            run:
              gsutil rsync ${{ secrets.BUCKET_URL }}/assets/data assets/data
  
          - name: Login to Artifact Registry
            uses: docker/login-action@v1
            with:
              registry: europe-west1-docker.pkg.dev
              username: oauth2accesstoken
              password: ${{ steps.auth.outputs.access_token }}
  
          - name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: .
              tags: europe-west1-docker.pkg.dev/mynearestleedsmarginal-prod/docker/mynearestleedsmarg:${{github.sha}}
              push: true
              file: dockerfiles/Dockerfile

          - name: Deploy to Google Cloud Run
            uses: 'google-github-actions/deploy-cloudrun@v1'
            with:
              service: 'mynearestleedsmarginal-deploy'
              image: europe-west1-docker.pkg.dev/mynearestleedsmarginal-prod/docker/mynearestleedsmarg:${{github.sha}}
